#!/bin/bash
set -e -x

mkdir -p tmp
cd tmp
NODE_VERSION=v0.10.32
NODE=node-$NODE_VERSION-darwin-x64
wget http://nodejs.org/dist/v0.10.32/$NODE.tar.gz
tar xzf $NODE.tar.gz
mkdir -p bin
cp tmp/$NODE/bin/node ./bin/hknode
cp tmp/$NODE/bin/node ./bin/hknpm
